CREATE TABLE data (
        degree DECIMAL NOT NULL,
        N DECIMAL NOT NULL,
        keywords VARCHAR NOT NULL,
        base_field_type VARCHAR NOT NULL,
        base_field_label VARCHAR NOT NULL,
        base_field_latex VARCHAR NOT NULL,
        base_field_degree BOOLEAN NOT NULL,
        sigma_inv_1 VARCHAR NOT NULL,
        sigma_inv_2 VARCHAR NOT NULL,
        sigma_inv_3 VARCHAR NOT NULL,
        label VARCHAR NOT NULL,
        citations VARCHAR NOT NULL,
        family VARCHAR NOT NULL,
        models_original_polys_vars VARCHAR NOT NULL,
        models_original_polys_val VARCHAR NOT NULL,
        models_original_polys_latex VARCHAR NOT NULL,
        models_original_resultant DECIMAL NOT NULL,
        models_original_name VARCHAR NOT NULL,
        models_original_bad_primes VARCHAR NOT NULL,
        models_original_height DECIMAL NOT NULL,
        models_original_base_field_label VARCHAR NOT NULL,
        models_original_base_field_latex VARCHAR NOT NULL,
        models_original_num_parameters BOOLEAN NOT NULL,
        models_original_conjugation_from_original_latex VARCHAR NOT NULL,
        models_original_conjugation_from_original_val VARCHAR NOT NULL,
        models_original_conjugation_from_original_base_field_label VARCHAR NOT NULL,
        models_original_conjugation_from_original_num_parameters BOOLEAN NOT NULL,
        display_model VARCHAR NOT NULL,
        is_morphism BOOLEAN NOT NULL,
        indeterminacy_locus_dimension DECIMAL NOT NULL,
        is_polynomial BOOLEAN NOT NULL,
        "models.monic_centered_polys_vars" VARCHAR NOT NULL,
        "models.monic_centered_polys_val" VARCHAR NOT NULL,
        "models.monic_centered_polys_latex" VARCHAR NOT NULL,
        "models.monic_centered_resultant" DECIMAL NOT NULL,
        "models.monic_centered_name" VARCHAR NOT NULL,
        "models.monic_centered_num_parameters" BOOLEAN NOT NULL,
        "models.monic_centered_bad_primes" VARCHAR NOT NULL,
        "models.monic_centered_height" DECIMAL NOT NULL,
        "models.monic_centered_conjugation_from_original_latex" VARCHAR NOT NULL,
        "models.monic_centered_conjugation_from_original_val" VARCHAR NOT NULL,
        "models.monic_centered_conjugation_from_original_base_field_label" VARCHAR NOT NULL,
        "models.monic_centered_conjugation_from_original_base_field_emb" BOOLEAN NOT NULL,
        "models.monic_centered_base_field_label" VARCHAR NOT NULL,
        "models.monic_centered_base_field_emb" BOOLEAN NOT NULL,
        "models.monic_centered_base_field_latex" VARCHAR NOT NULL,
        "models.Chebyshev_polys_vars" VARCHAR,
        "models.Chebyshev_polys_val" VARCHAR,
        "models.Chebyshev_polys_latex" VARCHAR,
        "models.Chebyshev_name" VARCHAR,
        "models.Chebyshev_height" DECIMAL,
        "models.Chebyshev_resultant" DECIMAL,
        "models.Chebyshev_conjugation_from_original_latex" VARCHAR,
        "models.Chebyshev_conjugation_from_original_val" VARCHAR,
        "models.Chebyshev_conjugation_from_original_base_field_label" VARCHAR,
        "models.Chebyshev_conjugation_from_original_base_field_emb" BOOLEAN,
        "models.Chebyshev_conjugation_from_original_num_parameters" BOOLEAN,
        "models.Chebyshev_base_field_label" VARCHAR,
        "models.Chebyshev_base_field_emb" BOOLEAN,
        "models.Chebyshev_base_field_latex" VARCHAR,
        "models.Chebyshev_num_parameters" BOOLEAN,
        is_Chebyshev BOOLEAN NOT NULL,
        is_Newton BOOLEAN NOT NULL,
        is_Lattes BOOLEAN NOT NULL,
        is_pcf BOOLEAN NOT NULL,
        automorphism_group_cardinality DECIMAL NOT NULL,
        automorphism_group_matrices VARCHAR NOT NULL
);